variables: 
  serviceConnectionDev: 'dev-germanywestcentral-sc'
  containerRegistryNameDev: 'acradosampledev'
  containerRegistryNameImportDev: 'acrimportdev'  # New variable for the destination ACR in DEV
  imageBaseName: hello-world
  imageNameDev: "$(containerRegistryNameDev).azurecr.io/$(imageBaseName):$(Build.BuildId)"
  imageNameImportDev: "$(containerRegistryNameImportDev).azurecr.io/$(imageBaseName):$(Build.BuildId)"

trigger:
  branches:
    include:
    - main

stages:
- stage: Build
  pool:
    vmImage: ubuntu-20.04

  jobs:
  - job: build
    displayName: Build
    steps:
    - task: AzureCLI@2
      displayName: Login to DEV ACR
      inputs:
        azureSubscription: $(serviceConnectionDev)
        scriptType: pscore
        addSpnToEnvironment: true
        scriptLocation: inlineScript
        inlineScript: |
          az acr login --name $(containerRegistryNameDev)

    - task: AzureCLI@2
      displayName: Build and Push to DEV ACR
      inputs:
        azureSubscription: $(serviceConnectionDev)
        scriptType: pscore
        scriptLocation: inlineScript
        inlineScript: |
          docker build -t $(imageNameDev) .
          docker push $(imageNameDev)

- stage: DeployToDev
  dependsOn: Build
  condition: succeeded()
  displayName: Deploy to Dev
  pool:
    vmImage: ubuntu-20.04

  jobs:
  - job: deploy

    steps:
    - pwsh: Write-Host "Here you can deploy the container to your favorite target. For example, AKS, ACI, ACA or Azure Web App for Containers."
      displayName: Deploy container to target platform

- stage: ImportToDev
  dependsOn: Build
  condition: succeeded()
  displayName: Import Image to another DEV ACR
  pool:
    vmImage: ubuntu-20.04

  jobs:
  - job: importToDevAcr
    displayName: Import Image to Import ACR in DEV
    steps:
    - task: AzureCLI@2
      displayName: Import Image to another DEV ACR
      inputs:
        azureSubscription: $(serviceConnectionDev)
        scriptType: pscore
        scriptLocation: inlineScript
        inlineScript: |
          $sourceImage = "$(containerRegistryNameDev).azurecr.io/$(imageBaseName):$(Build.BuildId)"
          $destinationImage = "$(containerRegistryNameImportDev).azurecr.io/$(imageBaseName):$(Build.BuildId)"
          
          # Log in to Import ACR in DEV
          az acr login --name $(containerRegistryNameImportDev)

          # Import the image from DEV ACR to another ACR in DEV
          az acr import `
          --name $(containerRegistryNameImportDev) `
          --source $sourceImage `
          --image $destinationImage
